fieldLayouts:
  fdf65357-60bd-413c-947f-7ce545753073:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 948d4c6a-e690-48e2-bcfe-09ce56596a26 # Inhalt
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Allgemein
        sortOrder: 1
handle: datenschutz
hasTitleField: false
name: Datenschutz
section: d52365af-0bef-4323-8738-3f94499584f7 # Datenschutz
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
