columnSuffix: null
contentColumnType: smallint(1)
fieldGroup: 42f5454d-dde0-4885-ac1a-70de5060e3f1 # Globals
handle: anzahlFeiertageImFooter
instructions: 'Definiert die Anzahl Feiertage, die im Footer angezeigt werden'
name: 'Anzahl Feiertage im Footer'
searchable: true
settings:
  decimals: 0
  defaultValue: 2
  max: 9
  min: 1
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
