columnSuffix: null
contentColumnType: datetime
fieldGroup: e6191f73-14c0-4002-875d-7413cf14aa0a # Events
handle: datumVon
instructions: ''
name: 'Datum von'
searchable: true
settings:
  max: null
  min: null
  minuteIncrement: '30'
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
