columnSuffix: null
contentColumnType: string
fieldGroup: cfcccbc2-fbbe-4175-afdb-d4a6f2f06418 # Common
handle: feiertage
instructions: ''
name: Feiertage
searchable: true
settings:
  contentTable: '{{%matrixcontent_feiertage}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
