columnSuffix: null
contentColumnType: text
fieldGroup: cfcccbc2-fbbe-4175-afdb-d4a6f2f06418 # Common
handle: homepage
instructions: ''
name: Homepage
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: www.
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
