columnSuffix: null
contentColumnType: text
fieldGroup: 42f5454d-dde0-4885-ac1a-70de5060e3f1 # Globals
handle: plzOrt
instructions: ''
name: 'PLZ / Ort'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
