defaultPlacement: end
enableVersioning: true
handle: anreise
name: Anreise
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  e7b28ff3-21a8-4e56-882a-64e296484ce4: # Einkaufszentrum Oberdorf
    enabledByDefault: true
    hasUrls: true
    template: _anreise
    uriFormat: anreise
type: single
